platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: latest

inputs: 
- name: flight-school

run:
  path: chmod +x .fligh-school/ci/test.sh
  path: ./flight-school/ci/test.sh

